### PR TITLE
EX-86 Fix features and about pages

### PR DESCRIPTION
**Pull request by nomadicoder**

### CODE REVIEW

**Comment by sensei100** [comment]
@nomadicoder I noticed that you are removing all the spec files and the yarn.lock.  Are those changes intentional?  You won't be able to run specs in the future without spec_helper, etc.

**Comment by nomadicoder** [comment]
@sensei100 Those were lost when I upgraded to the latest version of Spotlight. I would like to put them back in v0.0.9 or v0.1.0 which ever comes next. For now, can we merge this version, since that is what Gabe will be evaluating for the next two weeks?

**Comment by nomadicoder** [comment]
On hold.  Investigate why iiif model are no longer here.  Was the code deprecated by Spotlight, or is is something we added.

**Comment by nomadicoder** [comment]
@sensei100 After further examination, the models and respective specs were removed because Spotlight moved that iiif harvesting to it's own resource.  The iiif models have since been removed and we no longer require those tests.

**Comment by sensei100** [comment]
@nomadicoder The problem that I still have with this PR is that the yarn.lock file as well as the spec_helper and rails_helper files have all been removed.  Those are all basic files that need to remain as part of the code.

**Comment by nomadicoder** [comment]
@sensei100 I can rebuild the spec directory. But I wonder what happened to the yarn.lock file.  It's in my local build directory, but it's missing from the PR?  I see it in the branch here: https://github.com/tulibraries/tul_spotlight/blob/EX-86-Fix_features_and_about_pages/yarn.lock

**Comment by sensei100** [comment]
@nomadicoder I must be going crazy.  I thought it looked like the files were being removed, but when I view them I see that they are still there.

**Review by sensei100 — APPROVED** [review]

**Pull request merged**
